<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Funding Opportunities</name>
   <tag></tag>
   <elementGuidId>7e6ef66f-081e-494c-9175-c4a24cb622bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#igmsEleId46</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(@href, 'dashboard_fopp.do?resetPage=true')])[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = 'dashboard_fopp.do?resetPage=true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d531b064-d8c8-44ba-97bc-31ea5b4f2405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>dashboard_fopp.do?resetPage=true</value>
      <webElementGuid>7a7f576a-02e0-4ae7-886e-1b580c59dd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>igmsEleId46</value>
      <webElementGuid>2bbd89f9-49d4-469f-9ab1-b04b10ec752b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Funding Opportunities 67</value>
      <webElementGuid>00c9493c-4a41-4dc7-9f9b-0ee028730e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;igmsEleId46&quot;)</value>
      <webElementGuid>948cba31-b876-4ec8-8679-b6af6fdc50ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='igmsEleId46']</value>
      <webElementGuid>50e7f98f-e7ea-4c10-b3ba-ec9305a052b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseOne']/div/ul/li/a</value>
      <webElementGuid>032404ea-f902-4c48-b50d-bb61a8f01e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[2]</value>
      <webElementGuid>62aaa6bf-d87c-44a1-a577-48c7097d80c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'dashboard_fopp.do?resetPage=true')])[3]</value>
      <webElementGuid>7753b9dd-3589-4c41-bf02-b540845b1d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/ul/li/a</value>
      <webElementGuid>b61db7e2-b581-4e6f-b86c-8af49083bf30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'dashboard_fopp.do?resetPage=true' and @id = 'igmsEleId46' and (text() = 'Funding Opportunities 67' or . = 'Funding Opportunities 67')]</value>
      <webElementGuid>9ab5c4b4-b06c-424c-8f99-d6d390d96f4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
