<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dashboard</name>
   <tag></tag>
   <elementGuidId>536c243e-ba59-43fd-aa62-ad46f6b95970</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#igmsEleId6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Dashboard')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0a561457-9808-4488-bd1a-01c8cdead40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>main.do</value>
      <webElementGuid>c0f61c2a-8c94-44ab-9acc-2c0844c35d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Click to go to the main dashboard.</value>
      <webElementGuid>f0ad970d-2fcf-418b-b77f-1bf626262944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>igmsEleId6</value>
      <webElementGuid>67e4a7ef-239e-4538-aa2d-dfc28b06b410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>a25bb280-5c01-4cb3-b06b-421cb6fefb9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;igmsEleId6&quot;)</value>
      <webElementGuid>2d4e20df-58f5-4315-b1f7-2f34aaa9abd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='igmsEleId6']</value>
      <webElementGuid>3e62e033-dcb2-4687-8948-e3f5d5a6ed05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='igmsscreen']/div[3]/div/ul/li/a</value>
      <webElementGuid>82f92c85-a23f-49ef-abe2-acabff0d460f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dashboard')]</value>
      <webElementGuid>a3220ff5-2fb6-4026-80d6-2209db0c482f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press tab to continue and exit these instructions.'])[1]/following::a[1]</value>
      <webElementGuid>12804163-de9c-45b9-b5a3-5a116e40e192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub-level menu'])[1]/following::a[1]</value>
      <webElementGuid>791b21f7-3e61-4731-954c-c9547aa1e486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pre-Award'])[1]/preceding::a[1]</value>
      <webElementGuid>131cc89f-f30b-4d33-a90d-849e29fec238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funding Opportunities'])[1]/preceding::a[2]</value>
      <webElementGuid>a39fd937-6036-467a-9457-00e82bc92947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dashboard']/parent::*</value>
      <webElementGuid>bdca6069-37dc-4017-bdff-cf3d3ca26fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'main.do')])[2]</value>
      <webElementGuid>b447bd98-95fc-405e-bbbe-517b1252ffe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>f1067f3c-d023-4d61-a5e4-f2662a29981e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'main.do' and @alt = 'Click to go to the main dashboard.' and @id = 'igmsEleId6' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>6305e090-6950-4d4b-aa6d-fceb6f2a20b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
