<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search</name>
   <tag></tag>
   <elementGuidId>fe202d14-9228-4d28-90bb-da4978400fd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#igmsEleId46</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Search')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ef96724f-0a67-4f49-9f4e-4493ee810f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>search_fop.do?resetPage=true</value>
      <webElementGuid>0f000b68-c448-47d0-9f57-110230877de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>igmsEleId46</value>
      <webElementGuid>27bf8842-e8db-41ac-9521-bf9750b5f870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>278c884f-b751-4898-8c52-703f925661f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;igmsEleId46&quot;)</value>
      <webElementGuid>9d2f10e4-4f69-4bb2-8ade-45a5357e2652</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='igmsEleId46']</value>
      <webElementGuid>031e65ff-c212-492c-baef-54ea95c0cdda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='igmsscreen']/div[4]/div/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>e164509c-4c48-4e58-88f0-c250b818b455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Search')]</value>
      <webElementGuid>b9fbbc7b-e513-476f-978d-10565c8bd632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Tasks'])[1]/following::a[1]</value>
      <webElementGuid>955493e8-284e-4944-aa24-9d39b0556048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funding Opportunities'])[2]/following::a[2]</value>
      <webElementGuid>15330211-14fa-4eb4-bcb8-068470cfb3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assigned 67'])[2]/preceding::a[2]</value>
      <webElementGuid>fb0d3d48-755f-45f4-9ff1-d2444f800570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>b4115343-bcd4-4518-ad8a-ad0921be8a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'search_fop.do?resetPage=true')]</value>
      <webElementGuid>9e6617da-2ff6-4059-bd74-cc3c83a2fc0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>eae5beed-90c1-41c5-a859-df5607220a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'search_fop.do?resetPage=true' and @id = 'igmsEleId46' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>8672cff4-0346-45cc-bc18-693b7e189d7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
