<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>10977d06-3812-4448-a958-deca2bcc265a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='searchButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cefc7aab-d0d2-4a05-becf-ba15cb90a042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchButton</value>
      <webElementGuid>b3dc72c6-29c2-44e4-97b6-7ce0844e6d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b36ebd4e-add9-4eeb-a901-c2416548e2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>2f36b4d7-cb63-45d9-b648-1ad8656a684f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:submitForm();</value>
      <webElementGuid>7766fe01-36de-450c-bc6f-7910f2e15b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>83c54c5b-7077-4940-a087-741ca981ff68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchButton&quot;)</value>
      <webElementGuid>978dfffc-6eb4-4086-b9f7-ebcfeb38a5c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='searchButton']</value>
      <webElementGuid>95241d75-0de3-4b0c-89d1-1783b164bfc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dashbordSearchForm']/div/button</value>
      <webElementGuid>762fc96b-1e4b-4dae-8dd8-650291e3fe72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::button[1]</value>
      <webElementGuid>9a438124-4ffb-453d-b222-f77886163878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>308eb255-bf82-48f8-b407-59d7271bad60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'searchButton' and @type = 'button' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>fbb2fa5f-bd71-486e-bf2c-7e5b2d34181b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
